export const ADD_TOPIC = 'ADD_TOPIC'
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS'
export const ADD_TOPIC_ERROR = 'ADD_TOPIC_ERROR'

export const EDIT_TOPIC = 'EDIT_TOPIC'
export const EDIT_TOPIC_SUCCESS = 'EDIT_TOPIC_SUCCESS'
export const EDIT_TOPIC_ERROR = 'EDIT_TOPIC_ERROR'

export const UPDATE_TOPIC = 'UPDATE_TOPIC'
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS'
export const UPDATE_TOPIC_ERROR = 'UPDATE_TOPIC_ERROR'

export const DELETE_TOPIC = 'DELETE_TOPIC'
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS'
export const DELETE_TOPIC_ERROR = 'DELETE_TOPIC_ERROR'

export const LIST_TOPICS = 'LIST_TOPICS'
export const LIST_TOPICS_SUCCESS = 'LIST_TOPICS_SUCCESS'
export const LIST_TOPICS_ERROR = 'LIST_TOPICS_ERROR'
