
export const ADD_TOPIC = 'ADD_TOPIC_REQUEST';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_FAILURE = 'ADD_TOPIC_FAILURE';

export const EDIT_TOPIC = 'EDIT_TOPIC';
export const EDIT_TOPIC_SUCCESS = 'EDIT_TOPIC_SUCCESS';
export const EDIT_TOPIC_FAILURE = 'EDIT_TOPIC_FAILURE';

export const LIST_TOPICS = 'LIST_TOPICS';