export const ADD_LINK = 'ADD_LINK_REQUEST'
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS'
export const ADD_LINK_ERROR = 'ADD_LINK_ERROR'

export const LIST_LINKS = 'LIST_LINKS'
export const LIST_LINKS_SUCCESS = 'LIST_LINKS_SUCCESS'
export const LIST_LINKS_ERROR = 'LIST_LINKS_ERROR'

export const EDIT_LINK = 'EDIT_LINK'
export const EDIT_LINK_SUCCESS = 'EDIT_LINK_SUCCESS'
export const EDIT_LINK_ERROR = 'EDIT_LINK_ERROR'

export const UPDATE_LINK = 'UPDATE_LINK'
export const UPDATE_LINK_SUCCESS = 'UPDATE_LINK_SUCCESS'
export const UPDATE_LINK_ERROR = 'UPDATE_LINK_ERROR'

export const DELETE_LINK = 'DELETE_LINK'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
export const DELETE_LINK_ERROR = 'DELETE_LINK_ERROR'
